# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test API server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node-version: [18]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Upgrade NPM
      run: npm install -g npm
    - run: npm ci
    - run: npm test
  
  windows:      
    runs-on: windows-latest
    steps:
      - name: Checkout
        run: |
          mkdir C:/geoapipt.git
          git clone https://github.com/jfoclpf/geoapi.pt.git C:/geoapipt.git --depth 1
      - name: Upgrade NPM
        working-directory: C:/geoapipt.git
        run: npm install -g npm
      - name: Install dependencies
        working-directory: C:/geoapipt.git
        run: npm ci
      - name: Test
        working-directory: C:/geoapipt.git
        run: npm test
